<?php
	$productid = Mage::app()->getRequest()->getParam('id');
	$model = Mage::getModel('catalog/product'); //getting product model
	$_product = $model->load($productid); //getting product object for particular product id
?>
<table cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td style="text-align:left;" class="" colspan="2">
			<a href="#" class="pb_close "></a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<table cellpadding="0" cellspacing="0" width="100%">
				<tr>
					<td>	
						<div class="quick-product-img-box">
							<img title="<?php echo $_product->getName() ?>" alt="<?php echo $_product->getName() ?>" src="<?php echo $_product->getImageUrl() ?>"></p>
						</div>
					</td>
					<td>
						<div class="product-shop">
							<div class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName() ?></a>
							</div>

							
							<div class="qview-info-box">
								<div class="price-box quick-price-box">
									<span class="regular-price">
										<span class="price"><?php echo $this->getProductPrice($_product); ?></span>
									</span>
								</div>
								<?php
									if($_product->isSaleable())	{
								?>
								<div class="add-to-cart">
									<label for="qty">Qty:</label>
									<input type="text" class="input-text qty" title="Qty" value="1" maxlength="12" id="qty_<?php echo $productid ?>" name="qty">
									<?php 
										if($_product->stock_item->is_in_stock == 1){
											echo '<p class="in-stock"><span>'.$this->__('Availability: In stock.').'</span></p>';
										}else{
											echo '<p class="in-stock"><span>'.$this->__('Availability: Temporarily out of stock.').'</span></p>';
										}
									?>
									<button class="button btn-cart quick_add_cart" id="pb_cart_<?php echo $_product->getId() ?>" title="Buy Now" type="button"><span class="quick-add">BUY NOW</span></button>
								</div>
								<?php
									}
								?>
								<a href="<?php echo $_product->getProductUrl(); ?>" class="show-more-detail" title="See more details">Show More Details »</a>
							</div>
						</div>
						<!--  
						<div class="short-description" style="margin-top:15px;">
							<h2 class="hd">Quick Overview</h2>
							<div class="std"><?php //echo $_product->getShortDescription() ?></div>
						</div>
						-->
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="qview-footer">
                    <span>Free Shipping</span>&nbsp;|&nbsp;<span>Cash On Delivery </span>&nbsp;|&nbsp;<span>Customer Support(24x7) <strong>0124-6128000</strong></span>
    		</div>
		</td>
	</tr>

</table>